# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c32bc1a282b35f1b030de069edc34e44c443f7b21c09adeca3a0862893cc1d738b22f41ec30e50d4335ea729e08986db0f8805bd49f0935cabe5e8b32719782

test:
  secret_key_base: 4ab874244b24a849eb3bacefd68f64638917984555d45944035f138c44ed27e5222ee5582f90ce9c5c7999a0c232d556baaee985689cf699cc3b867cac798261

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
